### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by Vadammt** [jgile/vue-csv-import#1]
I cannot fiddle with the sampe (in `docs`) because build the project fails.

My system (from verbose log file):
 - Windows_NT 10.0.17134
 - node v8.11.3
 - npm  v5.6.0
 - vue-csv-import-1.5.1

Output when running **npm install dev**:
```
vue-csv-import-1.5.1> npm install dev
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.2: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Simon\AppData\Roaming\npm-cache\_logs\2018-07-29T10_09_08_220Z-debug.log
```

---

Output ``npm install`` (without dev):
```
vue-csv-import-1.5.1> npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> vue-csv-import@1.5.1 prepublish C:\Users\Vadammt\Development\vue-csv-import-1.5.1
> npm run test; npm run build

npm ERR! missing script: test;

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vadammt\AppData\Roaming\npm-cache\_logs\2018-07-29T10_12_07_054Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-csv-import@1.5.1 prepublish: `npm run test; npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-csv-import@1.5.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vadammt\AppData\Roaming\npm-cache\_logs\2018-07-29T10_12_07_137Z-debug.log
```

In the `2018-07-29T10_12_07_137Z-debug.log`:
```
...
26833 silly prepublish vue-csv-import@1.5.1
26834 warn prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
26835 warn prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
26836 warn prepublish-on-install See the deprecation note in `npm help scripts` for more information.
26837 info lifecycle vue-csv-import@1.5.1~prepublish: vue-csv-import@1.5.1
26838 verbose lifecycle vue-csv-import@1.5.1~prepublish: unsafe-perm in lifecycle true
26839 verbose lifecycle vue-csv-import@1.5.1~prepublish: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Vadammt\Development\vue-csv-import-1.5.1\node_modules\.bin;C:\Program Files\Python27\;C:\Program Files\Python27\Scripts;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Bitnami\wampstack-7.1.19-0\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Andy;C:\WINDOWS\SysWOW64;C:\WINDOWS\System32;C:\WINDOWS\SysWOW64\wbem;C:\WINDOWS\System32\wbem;C:\WINDOWS\SysWOW64\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files\Java\jdk1.8.0_162\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Vadammt\AppData\Local\Microsoft\WindowsApps;C:\Users\Vadammt\AppData\Roaming\Composer\vendor\bin;C:\Users\Vadammt\AppData\Local\atom\bin;c:\Users\Vadammt\AppData\Local\atom\bin;C:\Users\Vadammt\AppData\Local\GitHubDesktop\bin;C:\Users\Vadammt\AppData\Local\Microsoft\WindowsApps;C:\Users\Vadammt\AppData\Roaming\npm
26840 verbose lifecycle vue-csv-import@1.5.1~prepublish: CWD: C:\Users\Vadammt\Development\vue-csv-import-1.5.1
26841 silly lifecycle vue-csv-import@1.5.1~prepublish: Args: [ '/d /s /c', 'npm run test; npm run build' ]
26842 silly lifecycle vue-csv-import@1.5.1~prepublish: Returned: code: 1  signal: null
26843 info lifecycle vue-csv-import@1.5.1~prepublish: Failed to exec prepublish script
26844 verbose stack Error: vue-csv-import@1.5.1 prepublish: `npm run test; npm run build`
26844 verbose stack Exit status 1
26844 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
26844 verbose stack     at emitTwo (events.js:126:13)
26844 verbose stack     at EventEmitter.emit (events.js:214:7)
26844 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
26844 verbose stack     at emitTwo (events.js:126:13)
26844 verbose stack     at ChildProcess.emit (events.js:214:7)
26844 verbose stack     at maybeClose (internal/child_process.js:925:16)
26844 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
26845 verbose pkgid vue-csv-import@1.5.1
...
```

**Comment by Vadammt** [comment]
I found one problem in file ``package.json``:
Line 9: Windows has no ``rm`` command, so I changed it to: 
```
    "build": "del /F/S dist && NODE_ENV=production webpack",
```

**Comment by jgile** [comment]
updated to use vue-cli
